name: Deploy to Dokku
author: Bycoders
description: Push changes to Dokku server to automatically deploy the application.
branding:
  icon: server
  color: blue
inputs:
  PRIVATE_KEY:
    description: Private key to use for SSH authentication.
    required: true
  PUBLIC_KEY:
    description: Public key to use for SSH authentication.
    required: true
  PROJECT:
    description: Name of the application (as created in Dokku).
    required: true
  HOST:
    descripion: Domain (or IP address) where the application will be deployed.
    required: true
  BRANCH:
    description: Branch used to deploy the application.
    required: true
    default: master
  PROJECT_TYPE:
    description: (Optional) ruby, node, java, python
    required: false
    default: ruby
  POSTGRES:
    description: (Optional) true - Set up a postgres instance (Make sure that your app is using default DATABASE_URL env variable)
    required: false
    default: false
  REDIS:
    description: (Optional) true - Set up a redis instance (Make sure that your app is using default REDIS_URL env variable)
    required: false
    default: false
  ELASTICSEARCH:
    description: (Optional) true - Set up a elasticsearch instance (Make sure that your app is using default ELASTICSEARCH_URL env variable)
    required: false
    default: false
  MONGO:
    description: (Optional) true - Set up a mongo instance and link to app using the MONGO_URL environment variable
    required: false
    default: false
  REVIEW_APP:
    description: true - Set if deploy generates a new app (with branch name)
    required: true
    default: true

runs:
  using: docker
  image: Dockerfile
